# -*- coding: utf-8 -*-
"""pencil sketch using pyhton

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJ7Hpmga3rb1Kdhae-ltQiLfecxTRtEg

# LetsGrowMore Data Science Virtual Internship Program-2021
# Author:- Sourabh Sharma
# Beginner Level 
# Task: Image to Pencil Sketch with Python

# Firstly Lets load the libraries
"""

import cv2

from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt

"""# Now lets read the image"""

image=cv2.imread("/content/taskimg.py.jpg")
cv2_imshow(image)

"""# In the next step we need to convert the image into grey scale image.
So we will convert the RGB image to Gray scale image



"""

gray_scale_image=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY) 
cv2_imshow(gray_scale_image)

"""# In the Next step we will be Inverting the gray scale image
For doing this we will use the function called as bitwise_not function to invert the image



"""

inverted_image = cv2.bitwise_not(gray_scale_image)  
cv2_imshow(inverted_image)

"""# Now we will do the Image smoothing

In this we will be using the gaussian blur technique and the default sigma values filter on the image to smoothen our image.
"""

img_smoothing = cv2.GaussianBlur(inverted_image, (21, 21),sigmaX=0, sigmaY=0)
cv2_imshow(img_smoothing)

"""# Now we have reached at the final stage where we will be making the final pencil sketch
We will be dividing the greyscale value of the image by the inverse of blurred image value which highlights the boldest edges of an image.
"""

def pencil_sketch(x, y):

    return cv2.divide(x, 255 - y, scale=256)

pencil_sketch=pencil_sketch(gray_scale_image,img_smoothing)
cv2_imshow(pencil_sketch)

"""# Difference between normal image and pencil sketch!!"""

cv2_imshow(image)
cv2_imshow(pencil_sketch)

"""
## **Image to Pencil Sketch with Python is done successfully!!**"""